### ISSUE TITLE
Support RPM distributions directly from Repositories

### ISSUE THREAD

**Issue by 514amir** [pulp/squeezer#131]
Pulp seems to support making a distribution directly from a repository skipping the publication, can I propose that when creating a distribution you have the option to define a repository at which point the distribution reflects the latest state of the repository.

**Comment by netsandbox** [comment]
4bbb69e added the `autopublish` option to `rpm_repository`.
Especially here it makes sense to configure a `repository` instead of a `publication` for `rpm_distribution`, to let pulp find the latest publication for the repository.

see also https://docs.pulpproject.org/pulp_rpm/restapi.html#tag/Distributions:-Rpm/operation/distributions_rpm_rpm_create
