### ISSUE TITLE
Add retain_package_versions to rpm_repository.py

### ISSUE THREAD

**Issue by chtaylo2** [pulp/squeezer#154]
Hi,  Can we add "retain_package_versions" INTEGER as an optional key:pair for RPM Repository?

https://github.com/pulp/squeezer/blob/develop/plugins/modules/rpm_repository.py#L105
https://github.com/pulp/squeezer/blob/develop/plugins/modules/rpm_repository.py#L110

I would create a PR but i'm not sure what your requirements are for contributing.

Thank you

**Comment by mdellweg** [comment]
Oh, please go ahead. Mostly, I'd want to see a test for it (specifically so, since the module is still on the old codebase about to be rewritten for pulp_glue, and refactoring can only guarantee things covered by tests). Please consult the docs for writing and recording tests.
You should add yourself to the authors too.
And lastly (obviously) we need to get the CI green, so please stay around for that.

**Comment by chtaylo2** [comment]
@mdellweg - Thank you for the feedback. I've created the PR as planned. https://github.com/pulp/squeezer/pull/155

tests are included and passing 100%

**Comment by chtaylo2** [comment]
Closing issue. Thank you

**Comment by mdellweg** [comment]
Thank you!
